### ISSUE TITLE
Imagenes

### ISSUE THREAD

**Issue by JonathanC3** [JonathanC3/ServidorHttpHttps#1]
![Imagen1](https://user-images.githubusercontent.com/37557466/100564053-7f236f80-3285-11eb-9574-315f640f7e85.PNG)
![Imagen2](https://user-images.githubusercontent.com/37557466/100564859-c27edd80-3287-11eb-879e-4d62e85b30b8.PNG)
![image](https://user-images.githubusercontent.com/37557466/100564963-04a81f00-3288-11eb-896e-e9cd6af17b2b.png)
![imagen4](https://user-images.githubusercontent.com/37557466/100565165-94e66400-3288-11eb-9cdc-8c19f8703b04.PNG)
![imagen5](https://user-images.githubusercontent.com/37557466/100565376-16d68d00-3289-11eb-811a-94c80e7c509f.PNG)
![imagen6](https://user-images.githubusercontent.com/37557466/100565636-ad0ab300-3289-11eb-9c07-11d11f42676b.PNG)
![imagen7](https://user-images.githubusercontent.com/37557466/100565817-04a91e80-328a-11eb-9eb4-e6f944317a0d.PNG)
![imagen8](https://user-images.githubusercontent.com/37557466/100566017-8600b100-328a-11eb-88c5-a5d4a363c5b7.PNG)
![httpsCertCorrecto](https://user-images.githubusercontent.com/37557466/100566459-b1d06680-328b-11eb-964b-c7fd26b33c24.PNG)

**Comment by MariaOrocu** [comment]
![WhatsApp Image 2020-11-29 at 10 47 56 PM](https://user-images.githubusercontent.com/28690419/100569868-fc0a1580-3294-11eb-9910-0773577a25c4.jpeg)

**Comment by MariaOrocu** [comment]
![Captura de pantalla (11)](https://user-images.githubusercontent.com/28690419/100570692-f7466100-3296-11eb-9404-09b2886698f8.png)

**Comment by MariaOrocu** [comment]
![Captura de pantalla (12)](https://user-images.githubusercontent.com/28690419/100570774-265cd280-3297-11eb-84aa-bc24dc663935.png)

**Comment by MariaOrocu** [comment]
![Captura de pantalla (13)](https://user-images.githubusercontent.com/28690419/100570896-6e7bf500-3297-11eb-9543-015a715f0b89.png)

**Comment by MariaOrocu** [comment]
![Captura de pantalla (14)](https://user-images.githubusercontent.com/28690419/100570942-85224c00-3297-11eb-8772-9727bbb7a83c.png)
